//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brandbank.Api.ReportData {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Data ReportSoap", Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", ConfigurationName="ReportData.DataReportSoap")]
    public interface DataReportSoap {
        
        // CODEGEN: Generating message contract since message SupplyCoverageReportRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11/SupplyCoverageReport" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Brandbank.Api.ReportData.SupplyCoverageReportResponse SupplyCoverageReport(Brandbank.Api.ReportData.SupplyCoverageReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11/SupplyCoverageReport" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<Brandbank.Api.ReportData.SupplyCoverageReportResponse> SupplyCoverageReportAsync(Brandbank.Api.ReportData.SupplyCoverageReportRequest request);
        
        // CODEGEN: Generating message contract since message SupplyExtractionFeedbackRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11/SupplyExtractionFeed" +
            "back", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Brandbank.Api.ReportData.SupplyExtractionFeedbackResponse SupplyExtractionFeedback(Brandbank.Api.ReportData.SupplyExtractionFeedbackRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11/SupplyExtractionFeed" +
            "back", ReplyAction="*")]
        System.Threading.Tasks.Task<Brandbank.Api.ReportData.SupplyExtractionFeedbackResponse> SupplyExtractionFeedbackAsync(Brandbank.Api.ReportData.SupplyExtractionFeedbackRequest request);
        
        // CODEGEN: Generating message contract since message SupplyRawFileDataRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11/SupplyRawFileData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Brandbank.Api.ReportData.SupplyRawFileDataResponse SupplyRawFileData(Brandbank.Api.ReportData.SupplyRawFileDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11/SupplyRawFileData", ReplyAction="*")]
        System.Threading.Tasks.Task<Brandbank.Api.ReportData.SupplyRawFileDataResponse> SupplyRawFileDataAsync(Brandbank.Api.ReportData.SupplyRawFileDataRequest request);
        
        // CODEGEN: Generating message contract since message SupplyCompressedCoverageReportRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11/SupplyCompressedCove" +
            "rageReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Brandbank.Api.ReportData.SupplyCompressedCoverageReportResponse SupplyCompressedCoverageReport(Brandbank.Api.ReportData.SupplyCompressedCoverageReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11/SupplyCompressedCove" +
            "rageReport", ReplyAction="*")]
        System.Threading.Tasks.Task<Brandbank.Api.ReportData.SupplyCompressedCoverageReportResponse> SupplyCompressedCoverageReportAsync(Brandbank.Api.ReportData.SupplyCompressedCoverageReportRequest request);
        
        // CODEGEN: Generating message contract since message SupplyCompressedExtractionFeedbackRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11/SupplyCompressedExtr" +
            "actionFeedback", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Brandbank.Api.ReportData.SupplyCompressedExtractionFeedbackResponse SupplyCompressedExtractionFeedback(Brandbank.Api.ReportData.SupplyCompressedExtractionFeedbackRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11/SupplyCompressedExtr" +
            "actionFeedback", ReplyAction="*")]
        System.Threading.Tasks.Task<Brandbank.Api.ReportData.SupplyCompressedExtractionFeedbackResponse> SupplyCompressedExtractionFeedbackAsync(Brandbank.Api.ReportData.SupplyCompressedExtractionFeedbackRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11")]
    public partial class ExternalCallerHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid externalCallerIdField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid ExternalCallerId {
            get {
                return this.externalCallerIdField;
            }
            set {
                this.externalCallerIdField = value;
                this.RaisePropertyChanged("ExternalCallerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SupplyCoverageReport", WrapperNamespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", IsWrapped=true)]
    public partial class SupplyCoverageReportRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11")]
        public Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", Order=0)]
        public System.Xml.XmlNode xmlData;
        
        public SupplyCoverageReportRequest() {
        }
        
        public SupplyCoverageReportRequest(Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader, System.Xml.XmlNode xmlData) {
            this.ExternalCallerHeader = ExternalCallerHeader;
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SupplyCoverageReportResponse", WrapperNamespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", IsWrapped=true)]
    public partial class SupplyCoverageReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", Order=0)]
        public int SupplyCoverageReportResult;
        
        public SupplyCoverageReportResponse() {
        }
        
        public SupplyCoverageReportResponse(int SupplyCoverageReportResult) {
            this.SupplyCoverageReportResult = SupplyCoverageReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SupplyExtractionFeedback", WrapperNamespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", IsWrapped=true)]
    public partial class SupplyExtractionFeedbackRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11")]
        public Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", Order=0)]
        public System.Xml.XmlNode xmlData;
        
        public SupplyExtractionFeedbackRequest() {
        }
        
        public SupplyExtractionFeedbackRequest(Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader, System.Xml.XmlNode xmlData) {
            this.ExternalCallerHeader = ExternalCallerHeader;
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SupplyExtractionFeedbackResponse", WrapperNamespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", IsWrapped=true)]
    public partial class SupplyExtractionFeedbackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", Order=0)]
        public int SupplyExtractionFeedbackResult;
        
        public SupplyExtractionFeedbackResponse() {
        }
        
        public SupplyExtractionFeedbackResponse(int SupplyExtractionFeedbackResult) {
            this.SupplyExtractionFeedbackResult = SupplyExtractionFeedbackResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SupplyRawFileData", WrapperNamespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", IsWrapped=true)]
    public partial class SupplyRawFileDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11")]
        public Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] rawFileData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", Order=1)]
        public string usage;
        
        public SupplyRawFileDataRequest() {
        }
        
        public SupplyRawFileDataRequest(Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader, byte[] rawFileData, string usage) {
            this.ExternalCallerHeader = ExternalCallerHeader;
            this.rawFileData = rawFileData;
            this.usage = usage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SupplyRawFileDataResponse", WrapperNamespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", IsWrapped=true)]
    public partial class SupplyRawFileDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", Order=0)]
        public int SupplyRawFileDataResult;
        
        public SupplyRawFileDataResponse() {
        }
        
        public SupplyRawFileDataResponse(int SupplyRawFileDataResult) {
            this.SupplyRawFileDataResult = SupplyRawFileDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SupplyCompressedCoverageReport", WrapperNamespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", IsWrapped=true)]
    public partial class SupplyCompressedCoverageReportRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11")]
        public Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] rawFileData;
        
        public SupplyCompressedCoverageReportRequest() {
        }
        
        public SupplyCompressedCoverageReportRequest(Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader, byte[] rawFileData) {
            this.ExternalCallerHeader = ExternalCallerHeader;
            this.rawFileData = rawFileData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SupplyCompressedCoverageReportResponse", WrapperNamespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", IsWrapped=true)]
    public partial class SupplyCompressedCoverageReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", Order=0)]
        public int SupplyCompressedCoverageReportResult;
        
        public SupplyCompressedCoverageReportResponse() {
        }
        
        public SupplyCompressedCoverageReportResponse(int SupplyCompressedCoverageReportResult) {
            this.SupplyCompressedCoverageReportResult = SupplyCompressedCoverageReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SupplyCompressedExtractionFeedback", WrapperNamespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", IsWrapped=true)]
    public partial class SupplyCompressedExtractionFeedbackRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11")]
        public Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] rawFileData;
        
        public SupplyCompressedExtractionFeedbackRequest() {
        }
        
        public SupplyCompressedExtractionFeedbackRequest(Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader, byte[] rawFileData) {
            this.ExternalCallerHeader = ExternalCallerHeader;
            this.rawFileData = rawFileData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SupplyCompressedExtractionFeedbackResponse", WrapperNamespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", IsWrapped=true)]
    public partial class SupplyCompressedExtractionFeedbackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", Order=0)]
        public int SupplyCompressedExtractionFeedbackResult;
        
        public SupplyCompressedExtractionFeedbackResponse() {
        }
        
        public SupplyCompressedExtractionFeedbackResponse(int SupplyCompressedExtractionFeedbackResult) {
            this.SupplyCompressedExtractionFeedbackResult = SupplyCompressedExtractionFeedbackResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataReportSoapChannel : Brandbank.Api.ReportData.DataReportSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataReportSoapClient : System.ServiceModel.ClientBase<Brandbank.Api.ReportData.DataReportSoap>, Brandbank.Api.ReportData.DataReportSoap {
        
        public DataReportSoapClient() {
        }
        
        public DataReportSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataReportSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataReportSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataReportSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Brandbank.Api.ReportData.SupplyCoverageReportResponse Brandbank.Api.ReportData.DataReportSoap.SupplyCoverageReport(Brandbank.Api.ReportData.SupplyCoverageReportRequest request) {
            return base.Channel.SupplyCoverageReport(request);
        }
        
        public int SupplyCoverageReport(Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader, System.Xml.XmlNode xmlData) {
            Brandbank.Api.ReportData.SupplyCoverageReportRequest inValue = new Brandbank.Api.ReportData.SupplyCoverageReportRequest();
            inValue.ExternalCallerHeader = ExternalCallerHeader;
            inValue.xmlData = xmlData;
            Brandbank.Api.ReportData.SupplyCoverageReportResponse retVal = ((Brandbank.Api.ReportData.DataReportSoap)(this)).SupplyCoverageReport(inValue);
            return retVal.SupplyCoverageReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Brandbank.Api.ReportData.SupplyCoverageReportResponse> Brandbank.Api.ReportData.DataReportSoap.SupplyCoverageReportAsync(Brandbank.Api.ReportData.SupplyCoverageReportRequest request) {
            return base.Channel.SupplyCoverageReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<Brandbank.Api.ReportData.SupplyCoverageReportResponse> SupplyCoverageReportAsync(Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader, System.Xml.XmlNode xmlData) {
            Brandbank.Api.ReportData.SupplyCoverageReportRequest inValue = new Brandbank.Api.ReportData.SupplyCoverageReportRequest();
            inValue.ExternalCallerHeader = ExternalCallerHeader;
            inValue.xmlData = xmlData;
            return ((Brandbank.Api.ReportData.DataReportSoap)(this)).SupplyCoverageReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Brandbank.Api.ReportData.SupplyExtractionFeedbackResponse Brandbank.Api.ReportData.DataReportSoap.SupplyExtractionFeedback(Brandbank.Api.ReportData.SupplyExtractionFeedbackRequest request) {
            return base.Channel.SupplyExtractionFeedback(request);
        }
        
        public int SupplyExtractionFeedback(Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader, System.Xml.XmlNode xmlData) {
            Brandbank.Api.ReportData.SupplyExtractionFeedbackRequest inValue = new Brandbank.Api.ReportData.SupplyExtractionFeedbackRequest();
            inValue.ExternalCallerHeader = ExternalCallerHeader;
            inValue.xmlData = xmlData;
            Brandbank.Api.ReportData.SupplyExtractionFeedbackResponse retVal = ((Brandbank.Api.ReportData.DataReportSoap)(this)).SupplyExtractionFeedback(inValue);
            return retVal.SupplyExtractionFeedbackResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Brandbank.Api.ReportData.SupplyExtractionFeedbackResponse> Brandbank.Api.ReportData.DataReportSoap.SupplyExtractionFeedbackAsync(Brandbank.Api.ReportData.SupplyExtractionFeedbackRequest request) {
            return base.Channel.SupplyExtractionFeedbackAsync(request);
        }
        
        public System.Threading.Tasks.Task<Brandbank.Api.ReportData.SupplyExtractionFeedbackResponse> SupplyExtractionFeedbackAsync(Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader, System.Xml.XmlNode xmlData) {
            Brandbank.Api.ReportData.SupplyExtractionFeedbackRequest inValue = new Brandbank.Api.ReportData.SupplyExtractionFeedbackRequest();
            inValue.ExternalCallerHeader = ExternalCallerHeader;
            inValue.xmlData = xmlData;
            return ((Brandbank.Api.ReportData.DataReportSoap)(this)).SupplyExtractionFeedbackAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Brandbank.Api.ReportData.SupplyRawFileDataResponse Brandbank.Api.ReportData.DataReportSoap.SupplyRawFileData(Brandbank.Api.ReportData.SupplyRawFileDataRequest request) {
            return base.Channel.SupplyRawFileData(request);
        }
        
        public int SupplyRawFileData(Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader, byte[] rawFileData, string usage) {
            Brandbank.Api.ReportData.SupplyRawFileDataRequest inValue = new Brandbank.Api.ReportData.SupplyRawFileDataRequest();
            inValue.ExternalCallerHeader = ExternalCallerHeader;
            inValue.rawFileData = rawFileData;
            inValue.usage = usage;
            Brandbank.Api.ReportData.SupplyRawFileDataResponse retVal = ((Brandbank.Api.ReportData.DataReportSoap)(this)).SupplyRawFileData(inValue);
            return retVal.SupplyRawFileDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Brandbank.Api.ReportData.SupplyRawFileDataResponse> Brandbank.Api.ReportData.DataReportSoap.SupplyRawFileDataAsync(Brandbank.Api.ReportData.SupplyRawFileDataRequest request) {
            return base.Channel.SupplyRawFileDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Brandbank.Api.ReportData.SupplyRawFileDataResponse> SupplyRawFileDataAsync(Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader, byte[] rawFileData, string usage) {
            Brandbank.Api.ReportData.SupplyRawFileDataRequest inValue = new Brandbank.Api.ReportData.SupplyRawFileDataRequest();
            inValue.ExternalCallerHeader = ExternalCallerHeader;
            inValue.rawFileData = rawFileData;
            inValue.usage = usage;
            return ((Brandbank.Api.ReportData.DataReportSoap)(this)).SupplyRawFileDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Brandbank.Api.ReportData.SupplyCompressedCoverageReportResponse Brandbank.Api.ReportData.DataReportSoap.SupplyCompressedCoverageReport(Brandbank.Api.ReportData.SupplyCompressedCoverageReportRequest request) {
            return base.Channel.SupplyCompressedCoverageReport(request);
        }
        
        public int SupplyCompressedCoverageReport(Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader, byte[] rawFileData) {
            Brandbank.Api.ReportData.SupplyCompressedCoverageReportRequest inValue = new Brandbank.Api.ReportData.SupplyCompressedCoverageReportRequest();
            inValue.ExternalCallerHeader = ExternalCallerHeader;
            inValue.rawFileData = rawFileData;
            Brandbank.Api.ReportData.SupplyCompressedCoverageReportResponse retVal = ((Brandbank.Api.ReportData.DataReportSoap)(this)).SupplyCompressedCoverageReport(inValue);
            return retVal.SupplyCompressedCoverageReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Brandbank.Api.ReportData.SupplyCompressedCoverageReportResponse> Brandbank.Api.ReportData.DataReportSoap.SupplyCompressedCoverageReportAsync(Brandbank.Api.ReportData.SupplyCompressedCoverageReportRequest request) {
            return base.Channel.SupplyCompressedCoverageReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<Brandbank.Api.ReportData.SupplyCompressedCoverageReportResponse> SupplyCompressedCoverageReportAsync(Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader, byte[] rawFileData) {
            Brandbank.Api.ReportData.SupplyCompressedCoverageReportRequest inValue = new Brandbank.Api.ReportData.SupplyCompressedCoverageReportRequest();
            inValue.ExternalCallerHeader = ExternalCallerHeader;
            inValue.rawFileData = rawFileData;
            return ((Brandbank.Api.ReportData.DataReportSoap)(this)).SupplyCompressedCoverageReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Brandbank.Api.ReportData.SupplyCompressedExtractionFeedbackResponse Brandbank.Api.ReportData.DataReportSoap.SupplyCompressedExtractionFeedback(Brandbank.Api.ReportData.SupplyCompressedExtractionFeedbackRequest request) {
            return base.Channel.SupplyCompressedExtractionFeedback(request);
        }
        
        public int SupplyCompressedExtractionFeedback(Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader, byte[] rawFileData) {
            Brandbank.Api.ReportData.SupplyCompressedExtractionFeedbackRequest inValue = new Brandbank.Api.ReportData.SupplyCompressedExtractionFeedbackRequest();
            inValue.ExternalCallerHeader = ExternalCallerHeader;
            inValue.rawFileData = rawFileData;
            Brandbank.Api.ReportData.SupplyCompressedExtractionFeedbackResponse retVal = ((Brandbank.Api.ReportData.DataReportSoap)(this)).SupplyCompressedExtractionFeedback(inValue);
            return retVal.SupplyCompressedExtractionFeedbackResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Brandbank.Api.ReportData.SupplyCompressedExtractionFeedbackResponse> Brandbank.Api.ReportData.DataReportSoap.SupplyCompressedExtractionFeedbackAsync(Brandbank.Api.ReportData.SupplyCompressedExtractionFeedbackRequest request) {
            return base.Channel.SupplyCompressedExtractionFeedbackAsync(request);
        }
        
        public System.Threading.Tasks.Task<Brandbank.Api.ReportData.SupplyCompressedExtractionFeedbackResponse> SupplyCompressedExtractionFeedbackAsync(Brandbank.Api.ReportData.ExternalCallerHeader ExternalCallerHeader, byte[] rawFileData) {
            Brandbank.Api.ReportData.SupplyCompressedExtractionFeedbackRequest inValue = new Brandbank.Api.ReportData.SupplyCompressedExtractionFeedbackRequest();
            inValue.ExternalCallerHeader = ExternalCallerHeader;
            inValue.rawFileData = rawFileData;
            return ((Brandbank.Api.ReportData.DataReportSoap)(this)).SupplyCompressedExtractionFeedbackAsync(inValue);
        }
    }
}
