//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brandbank.Api.ExtractData {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Data ExtractSoap", Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", ConfigurationName="ExtractData.DataExtractSoap")]
    public interface DataExtractSoap {
        
        // CODEGEN: Generating message contract since message GetUnsentProductDataRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11/GetUnsentProductData" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Brandbank.Api.ExtractData.GetUnsentProductDataResponse GetUnsentProductData(Brandbank.Api.ExtractData.GetUnsentProductDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11/GetUnsentProductData" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<Brandbank.Api.ExtractData.GetUnsentProductDataResponse> GetUnsentProductDataAsync(Brandbank.Api.ExtractData.GetUnsentProductDataRequest request);
        
        // CODEGEN: Generating message contract since message GetProductDataForGTINsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11/GetProductDataForGTI" +
            "Ns", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Brandbank.Api.ExtractData.GetProductDataForGTINsResponse GetProductDataForGTINs(Brandbank.Api.ExtractData.GetProductDataForGTINsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11/GetProductDataForGTI" +
            "Ns", ReplyAction="*")]
        System.Threading.Tasks.Task<Brandbank.Api.ExtractData.GetProductDataForGTINsResponse> GetProductDataForGTINsAsync(Brandbank.Api.ExtractData.GetProductDataForGTINsRequest request);
        
        // CODEGEN: Generating message contract since message AcknowledgeMessageRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11/AcknowledgeMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Brandbank.Api.ExtractData.AcknowledgeMessageResponse AcknowledgeMessage(Brandbank.Api.ExtractData.AcknowledgeMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11/AcknowledgeMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Brandbank.Api.ExtractData.AcknowledgeMessageResponse> AcknowledgeMessageAsync(Brandbank.Api.ExtractData.AcknowledgeMessageRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11")]
    public partial class ExternalCallerHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid externalCallerIdField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid ExternalCallerId {
            get {
                return this.externalCallerIdField;
            }
            set {
                this.externalCallerIdField = value;
                this.RaisePropertyChanged("ExternalCallerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUnsentProductData", WrapperNamespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", IsWrapped=true)]
    public partial class GetUnsentProductDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11")]
        public Brandbank.Api.ExtractData.ExternalCallerHeader ExternalCallerHeader;
        
        public GetUnsentProductDataRequest() {
        }
        
        public GetUnsentProductDataRequest(Brandbank.Api.ExtractData.ExternalCallerHeader ExternalCallerHeader) {
            this.ExternalCallerHeader = ExternalCallerHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUnsentProductDataResponse", WrapperNamespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", IsWrapped=true)]
    public partial class GetUnsentProductDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", Order=0)]
        public System.Xml.XmlNode GetUnsentProductDataResult;
        
        public GetUnsentProductDataResponse() {
        }
        
        public GetUnsentProductDataResponse(System.Xml.XmlNode GetUnsentProductDataResult) {
            this.GetUnsentProductDataResult = GetUnsentProductDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductDataForGTINs", WrapperNamespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", IsWrapped=true)]
    public partial class GetProductDataForGTINsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11")]
        public Brandbank.Api.ExtractData.ExternalCallerHeader ExternalCallerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("gtin")]
        public string[] gtins;
        
        public GetProductDataForGTINsRequest() {
        }
        
        public GetProductDataForGTINsRequest(Brandbank.Api.ExtractData.ExternalCallerHeader ExternalCallerHeader, string[] gtins) {
            this.ExternalCallerHeader = ExternalCallerHeader;
            this.gtins = gtins;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductDataForGTINsResponse", WrapperNamespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", IsWrapped=true)]
    public partial class GetProductDataForGTINsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", Order=0)]
        public System.Xml.XmlNode GetProductDataForGTINsResult;
        
        public GetProductDataForGTINsResponse() {
        }
        
        public GetProductDataForGTINsResponse(System.Xml.XmlNode GetProductDataForGTINsResult) {
            this.GetProductDataForGTINsResult = GetProductDataForGTINsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AcknowledgeMessage", WrapperNamespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", IsWrapped=true)]
    public partial class AcknowledgeMessageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11")]
        public Brandbank.Api.ExtractData.ExternalCallerHeader ExternalCallerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", Order=0)]
        public System.Guid messageGuid;
        
        public AcknowledgeMessageRequest() {
        }
        
        public AcknowledgeMessageRequest(Brandbank.Api.ExtractData.ExternalCallerHeader ExternalCallerHeader, System.Guid messageGuid) {
            this.ExternalCallerHeader = ExternalCallerHeader;
            this.messageGuid = messageGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AcknowledgeMessageResponse", WrapperNamespace="http://www.i-label.net/Partners/WebServices/DataFeed/2005/11", IsWrapped=true)]
    public partial class AcknowledgeMessageResponse {
        
        public AcknowledgeMessageResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataExtractSoapChannel : Brandbank.Api.ExtractData.DataExtractSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataExtractSoapClient : System.ServiceModel.ClientBase<Brandbank.Api.ExtractData.DataExtractSoap>, Brandbank.Api.ExtractData.DataExtractSoap {
        
        public DataExtractSoapClient() {
        }
        
        public DataExtractSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataExtractSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataExtractSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataExtractSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Brandbank.Api.ExtractData.GetUnsentProductDataResponse Brandbank.Api.ExtractData.DataExtractSoap.GetUnsentProductData(Brandbank.Api.ExtractData.GetUnsentProductDataRequest request) {
            return base.Channel.GetUnsentProductData(request);
        }
        
        public System.Xml.XmlNode GetUnsentProductData(Brandbank.Api.ExtractData.ExternalCallerHeader ExternalCallerHeader) {
            Brandbank.Api.ExtractData.GetUnsentProductDataRequest inValue = new Brandbank.Api.ExtractData.GetUnsentProductDataRequest();
            inValue.ExternalCallerHeader = ExternalCallerHeader;
            Brandbank.Api.ExtractData.GetUnsentProductDataResponse retVal = ((Brandbank.Api.ExtractData.DataExtractSoap)(this)).GetUnsentProductData(inValue);
            return retVal.GetUnsentProductDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Brandbank.Api.ExtractData.GetUnsentProductDataResponse> Brandbank.Api.ExtractData.DataExtractSoap.GetUnsentProductDataAsync(Brandbank.Api.ExtractData.GetUnsentProductDataRequest request) {
            return base.Channel.GetUnsentProductDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Brandbank.Api.ExtractData.GetUnsentProductDataResponse> GetUnsentProductDataAsync(Brandbank.Api.ExtractData.ExternalCallerHeader ExternalCallerHeader) {
            Brandbank.Api.ExtractData.GetUnsentProductDataRequest inValue = new Brandbank.Api.ExtractData.GetUnsentProductDataRequest();
            inValue.ExternalCallerHeader = ExternalCallerHeader;
            return ((Brandbank.Api.ExtractData.DataExtractSoap)(this)).GetUnsentProductDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Brandbank.Api.ExtractData.GetProductDataForGTINsResponse Brandbank.Api.ExtractData.DataExtractSoap.GetProductDataForGTINs(Brandbank.Api.ExtractData.GetProductDataForGTINsRequest request) {
            return base.Channel.GetProductDataForGTINs(request);
        }
        
        public System.Xml.XmlNode GetProductDataForGTINs(Brandbank.Api.ExtractData.ExternalCallerHeader ExternalCallerHeader, string[] gtins) {
            Brandbank.Api.ExtractData.GetProductDataForGTINsRequest inValue = new Brandbank.Api.ExtractData.GetProductDataForGTINsRequest();
            inValue.ExternalCallerHeader = ExternalCallerHeader;
            inValue.gtins = gtins;
            Brandbank.Api.ExtractData.GetProductDataForGTINsResponse retVal = ((Brandbank.Api.ExtractData.DataExtractSoap)(this)).GetProductDataForGTINs(inValue);
            return retVal.GetProductDataForGTINsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Brandbank.Api.ExtractData.GetProductDataForGTINsResponse> Brandbank.Api.ExtractData.DataExtractSoap.GetProductDataForGTINsAsync(Brandbank.Api.ExtractData.GetProductDataForGTINsRequest request) {
            return base.Channel.GetProductDataForGTINsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Brandbank.Api.ExtractData.GetProductDataForGTINsResponse> GetProductDataForGTINsAsync(Brandbank.Api.ExtractData.ExternalCallerHeader ExternalCallerHeader, string[] gtins) {
            Brandbank.Api.ExtractData.GetProductDataForGTINsRequest inValue = new Brandbank.Api.ExtractData.GetProductDataForGTINsRequest();
            inValue.ExternalCallerHeader = ExternalCallerHeader;
            inValue.gtins = gtins;
            return ((Brandbank.Api.ExtractData.DataExtractSoap)(this)).GetProductDataForGTINsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Brandbank.Api.ExtractData.AcknowledgeMessageResponse Brandbank.Api.ExtractData.DataExtractSoap.AcknowledgeMessage(Brandbank.Api.ExtractData.AcknowledgeMessageRequest request) {
            return base.Channel.AcknowledgeMessage(request);
        }
        
        public void AcknowledgeMessage(Brandbank.Api.ExtractData.ExternalCallerHeader ExternalCallerHeader, System.Guid messageGuid) {
            Brandbank.Api.ExtractData.AcknowledgeMessageRequest inValue = new Brandbank.Api.ExtractData.AcknowledgeMessageRequest();
            inValue.ExternalCallerHeader = ExternalCallerHeader;
            inValue.messageGuid = messageGuid;
            Brandbank.Api.ExtractData.AcknowledgeMessageResponse retVal = ((Brandbank.Api.ExtractData.DataExtractSoap)(this)).AcknowledgeMessage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Brandbank.Api.ExtractData.AcknowledgeMessageResponse> Brandbank.Api.ExtractData.DataExtractSoap.AcknowledgeMessageAsync(Brandbank.Api.ExtractData.AcknowledgeMessageRequest request) {
            return base.Channel.AcknowledgeMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Brandbank.Api.ExtractData.AcknowledgeMessageResponse> AcknowledgeMessageAsync(Brandbank.Api.ExtractData.ExternalCallerHeader ExternalCallerHeader, System.Guid messageGuid) {
            Brandbank.Api.ExtractData.AcknowledgeMessageRequest inValue = new Brandbank.Api.ExtractData.AcknowledgeMessageRequest();
            inValue.ExternalCallerHeader = ExternalCallerHeader;
            inValue.messageGuid = messageGuid;
            return ((Brandbank.Api.ExtractData.DataExtractSoap)(this)).AcknowledgeMessageAsync(inValue);
        }
    }
}
